// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workwear.Data;

#nullable disable

namespace Workwear.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230602070941_AddedProduct")]
    partial class AddedProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workwear.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Штаны"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Обувь"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Комбинезон"
                        });
                });

            modelBuilder.Entity("Workwear.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "sdadasd",
                            Price = 500.0,
                            Title = "Штаны"
                        },
                        new
                        {
                            Id = 2,
                            Description = "aaaaaaaaaa",
                            Price = 200.0,
                            Title = "Обувь"
                        },
                        new
                        {
                            Id = 3,
                            Description = "bbbbbb",
                            Price = 350.0,
                            Title = "Комбинезон"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
