// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workwear.Data;

#nullable disable

namespace Workwear.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230602114110_AddedSizes")]
    partial class AddedSizes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workwear.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Штаны"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Обувь"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Комбинезон"
                        });
                });

            modelBuilder.Entity("Workwear.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "sdadasd",
                            ImageUrl = "",
                            Price = 500.0,
                            Title = "Штаны"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "aaaaaaaaaa",
                            ImageUrl = "",
                            Price = 200.0,
                            Title = "Обувь"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "bbbbbb",
                            ImageUrl = "",
                            Price = 350.0,
                            Title = "Комбинезон"
                        });
                });

            modelBuilder.Entity("Workwear.Models.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 10,
                            SizeName = "S"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Quantity = 15,
                            SizeName = "M"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Quantity = 5,
                            SizeName = "39"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            Quantity = 8,
                            SizeName = "40"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            Quantity = 12,
                            SizeName = "L"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            Quantity = 7,
                            SizeName = "XL"
                        });
                });

            modelBuilder.Entity("Workwear.Models.Product", b =>
                {
                    b.HasOne("Workwear.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Workwear.Models.ProductSize", b =>
                {
                    b.HasOne("Workwear.Models.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Workwear.Models.Product", b =>
                {
                    b.Navigation("ProductSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
